package WerewolfJudge;

// import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
// @Slf4j
public class UserRunner implements CommandLineRunner {
  // This line will be generated by the annotation @Slf4j, but currently vscode
  // does not support annotation preprocessing. To avoid `log` as undefined
  // error in editor, I will just add this line to make editor happy.
  private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(UserRunner.class);
  @Autowired private UserRepository repo;

  @Override
  public void run(String... args) throws Exception {
    log.info("show all the users");
    for (User u : repo.findAll()) {
      log.info("{}", u.toString());
    }
  }
}
